project:
  type: website
  output-dir: docs

about:
  template: solana
  image: images/headshot.jpg

website:
  title: "Maxine Paredes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



